management:
  server:
    port: 8080

spring:
  application:
    name: cardatabase

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/car-db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db-changelog-master.xml
    default-schema: public
    contexts: migrated

logging:
  level:
    root: debug

